# Tcl package index file
# This file is NOT generated by the "pkg_mkIndex" command 

set _name    DeviceRole
set _version 1.2

set _files {}
lappend _files "$dir/role.tcl"
lappend _files "$dir/d_keysight_gen.tcl"
lappend _files "$dir/r_noise_source.tcl"
lappend _files "$dir/r_ac_source.tcl"
lappend _files "$dir/r_dc_source.tcl"
lappend _files "$dir/r_burst_source.tcl"
lappend _files "$dir/r_power_supply.tcl"
lappend _files "$dir/r_gauge.tcl"

set _pcmd {}
foreach _f $_files { lappend _pcmd "source $_f" }
lappend _pcmd "package provide $_name $_version"
package ifneeded $_name $_version [join $_pcmd \n]

