# Tcl package index file
# This file is NOT generated by the "pkg_mkIndex" command 

set _name    DeviceRole
set _version 1.0
set _files   {\
 role\
 power_supply power_supply/keysight_n6700b power_supply/tenma_72-2550\
}

set _pcmd {}
foreach _f $_files { lappend _pcmd "source [file join $dir $_f.tcl]" }
lappend _pcmd "package provide $_name $_version"
package ifneeded $_name $_version [join $_pcmd \n]

