#!/usr/bin/tclsh

set files {}
lappend files role.tcl
lappend files {*}[lsort [glob {power_supply/*.tcl} ]]

foreach f $files { source "./$f" }

set dev [DeviceRole ps1 power_supply]

puts [$dev cc_reset]
after 100

$dev set_curr 0.2
puts [$dev get_curr]
puts [$dev get_stat]
